### ISSUE TITLE
Decide on chart-verifier versioning 

### ISSUE THREAD

**Issue by tetchel** [redhat-actions/chart-verifier#2]
With https://github.com/redhat-certification/chart-verifier/issues/33 we have to decide if/when to pick up new chart-verifier releases, or use `latest`. 

It may also be possible to take the `chart-verifier` version as an action input and pass it as a build ARG to the docker build. 

If this approach is used we should pick a version default and add a README section explaining why/how to use `latest`

**Comment by tetchel** [comment]
There are also the `profile` inputs https://github.com/redhat-actions/chart-verifier#inputs which could theoretically lock the rules, depending on how the chart-verifier team manages versioning those.

So, another solution would be to pick a profile and pass some defaults, so a user would have to override those by hand to get the latest rule set

**Comment by tetchel** [comment]
Another solution would be to pick a profile and pass some defaults, so a user would have to override those by hand to get the latest rule set

**Comment by divyansh42** [comment]
> It may also be possible to take the chart-verifier version as an action's input and pass it as a build ARG to the docker build.

This approach is not possible because GitHub actions do not support ARG yet in Dockerfile https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions
More details are available here https://github.community/t/feature-request-build-args-support-in-docker-container-actions/16846/16

**Comment by divyansh42** [comment]
We don't need this discussion as we'll re-write this action where the user can choose the chart verifier version.
https://github.com/redhat-actions/chart-verifier/issues/4
